---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 2985300290-qsIrb84n7Eajf9SZQKuRd8xhVPFFkVt1c8dV6pD
:access_token_secret: yxhbNFuPFkPQ1Pif9Y1AJLwlF97b8QhbKnYrGBhAGfka5
