# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 961b24e2d6cb40d911b99b9be2560e63468cf9e8972b60e50f919055c09e484e5d41292241cbcee9c9243d4344a8a3ea06f834a83d1bb7f1ef75f4e39f515a11

test:
  secret_key_base: 623d31bdf2f36983b53e13eaf12493d49ceaa4d0fac4489ae6c2970f52693fff83229108bd373a88a9235102568d8ca994fcd7b3281290c813cb7f5ef4af4306

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
